services:

  psql_keycloak:
    container_name: psql_keycloak
    image: postgres
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - keycloak_db:/data/postgres
    networks:
      - keycloak_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: ./keycloak/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - keycloak_network
      - backend_network
    depends_on:
      - psql_keycloak
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  eureka:
    container_name: eureka
    image: dnadas98/freeroam:eureka
    env_file:
      - ./.env
    ports:
      - "8761:8761"
    networks:
      - backend_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gateway:
    container_name: gateway
    image: dnadas98/freeroam:gateway
    env_file:
      - ./.env
    networks:
      - backend_network
    depends_on:
      - eureka
      - keycloak
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  summits_db:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${FREEROAM_SUMMITS_DB_NAME}"
      POSTGRES_USER: "${FREEROAM_SUMMITS_DB_USER}"
      POSTGRES_PASSWORD: "${FREEROAM_SUMMITS_DB_PASSWORD}"
    networks:
      - summits_network
    volumes:
      - summits_db:/var/lib/postgresql/data

  summits:
    container_name: summits
    image: dnadas98/freeroam:summits
    env_file:
      - ./.env
    networks:
      - summits_network
      - backend_network
    depends_on:
      - summits_db
      - gateway
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trails:
    container_name: trails
    image: dnadas98/freeroam:trails
    env_file:
      - ./.env
    networks:
      - backend_network
    depends_on:
      - gateway
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - backend_network
      - keycloak_network
    ports:
      - "4200:443"
    depends_on:
      - gateway
      - keycloak
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  keycloak_network:
    driver: bridge
  backend_network:
    driver: bridge
  summits_network:
    driver: bridge

volumes:
  keycloak_db:
  summits_db: